Issue #12 Testing modules solved.
NeuroSYS-pl/magda pull request #13
Opened 2021-05-31 12:49 UTC by lukaszsus

### Overview
Issue #12 solved:
https://github.com/NeuroSYS-pl/magda/issues/12

The issue's aim is to create a simple wrapper for [magda.module.Module.Runtime](https://github.com/NeuroSYS-pl/magda/blob/main/magda/module/module.py) called `ModuleTestingWrapper`. Its interface mimics [SequentialPipeline](https://github.com/NeuroSYS-pl/magda/blob/main/magda/pipeline/sequential.py) interface, but the whole class is much simpler, for example, it does not include building [Graph](https://github.com/NeuroSYS-pl/magda/blob/83bdaf3472eba7b9be6f8000b670ab50997d5a66/magda/pipeline/graph.py) which is responsible for running modules in normal magda's pipeline. `ModuleTestingWrapper` enables simple testing of modules due to automation of calling `bootstrap`, `teardown` methods and taking care of wrapping data object into [magda.module.results.ResultSet](https://github.com/NeuroSYS-pl/magda/blob/83bdaf3472eba7b9be6f8000b670ab50997d5a66/magda/module/results.py#L23) object.

2021-06-01 11:12 UTC, jamebs requested changes

2021-06-01 11:12 UTC, jamebs commented on magda/testing/module_testing_wrapper.py
> +        return list(sig.parameters.keys())
`module.run` has always the same set of arguments:

```py
class MyModule(Module.Runtime):
    def run(self, data: Module.ResultSet, request: Any, *args, **kwargs):
        pass
```

Checking the method signature is not needed here

2021-06-01 11:12 UTC, jamebs commented on magda/testing/utils.py
> +        return func(*args, **kwargs)
Add newline at the end of file

2021-06-01 11:12 UTC, jamebs commented on magda/testing/utils.py
> +    return args, kwargs
You can always pass `data`/`result set` to the module because the module will always be capable of handling it

2021-06-01 11:12 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +class TestTestingModule:
Rename to: `TestModuleTestingWrapper`

2021-06-01 11:12 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +        result = await mock.run(data=RawData('xyz'), request={'query': 'query'})
It should be: `... data=[RawData('xyz')] ...` (`mock.run` should accept only iterable input / list of input results)

2021-06-01 11:12 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +    async def test_should_correctyl_bootstrap(self, module_cls):
typo

2021-06-09 10:31 UTC, jamebs commented on magda/testing/utils.py
> +def wrap_into_result(result, name='', src_class=None, expose=None):
```suggestion
def wrap_into_result(result, name='testing-module', src_class=None, expose=None):
```

2021-06-09 10:36 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +        assert mock._request == request
Instead checking the internal `_request`, I'll patch `module.run` and check if it was called with a correct `request` as a argument

2021-06-09 10:37 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +        assert mock._data.collection[0].result.data == data.data
Same here - *patch* `module.run` method and check what was passed as argument

2021-06-09 10:39 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +class TestWrapIntoResult:
Move this class to a separate file, which will test *utils* (like `wrap_into_result`)

2021-06-11 12:29 UTC, lukaszsus commented on test/test_module_testing_wrapper.py
> +class TestWrapIntoResult:
Moved to `test/test_testing_utils.py` to distinguish `magda/testing/utils.py` from other files called `utils.py` that can appear in the future.

2021-06-11 13:56 UTC, lukaszsus commented on test/test_module_testing_wrapper.py
> +        assert mock._request == request
I am not fully convinced that this solution is much better. One of possible solutions requires implementing 4 'run_mock' functions:
- async and sync version for checking `request`,
- async and sync version for checking `data`.
Moreover, we are going to mock our own classes, written especially for tests. I think it will make the code little chaotic.

2021-06-14 07:12 UTC, lukaszsus commented on test/test_module_testing_wrapper.py
> +        assert mock._request == request
Finally, I have implemented this with `MagickMock`. :slightly_smiling_face: Please, check if current solution fits your expectations. ;-)

2021-06-14 07:25 UTC, lukaszsus commented on test/test_module_testing_wrapper.py
> +        assert mock._data.collection[0].result.data == data.data
Unfortunately, it isn't possible to implement this as I did in case of [test_should_correctly_set_request](https://github.com/NeuroSYS-pl/magda/pull/13#discussion_r650696871) because of the fact that we prepare `RawData` in the test function, but it is wrapped into ResultSet before being passed to `module.run` method.
Maybe, it is possible in some other way, but the MagickMock is the only one working, that I could find, and it is still quite elegant.

2021-06-14 14:04 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +        assert mock._data.collection[0].result.data == data.data
You could assert *ResultSet.result` is `RawData`, because ResultSet only wraps the provided data

2021-06-14 14:18 UTC, jamebs commented on test/test_module_testing_wrapper.py
> +        module._derived_class.run = MagicMock(return_value=ProcessedData('zyx'))
That's pretty ugly - you shouldn't relay on Module semi-private variable. How about:
1. `mock = await ModuleTestingWrapper(module).build()`
2. MagicMock `mock.run`
3. Check if `mock.run` was called with the same object `request`

You want to check just one option, because others (like building module) are covered by the previous tests

2021-06-14 14:20 UTC, jamebs commented on magda/testing/module_testing_wrapper.py
> +        self._data = ResultSet(results)
Not sure, which option will be more readable: this one or
```py
self._data = ResultSet([wrap_into_result(r) for r in data])
```

2021-06-18 14:09 UTC, jamebs requested changes
Looks fine! Just tiny 2 changes and we can merge it :smile:

2021-06-18 14:09 UTC, jamebs commented on test/test_testing_utils.py
> +    def test_should_pass(self):
```suggestion
    def test_should_wrap_data_into_result(self):
```

2021-06-18 14:09 UTC, jamebs commented on test/test_testing_utils.py
> +    def test_should_fail(self):
Test edge cases like:
- `test_should_rise_for_missing_data`
- `test_should_accept_missing_arguments`

2021-06-18 14:22 UTC, jamebs approved these changes

2021-06-18 14:23 UTC, jamebs commented
Excellent job! Thanks for your contribution! :clap:

2021-06-18 14:24 UTC, merged