Added result object pattern
NeuroSYS-pl/magda pull request #23
Opened 2021-08-20 14:41 UTC by p-mielniczuk

2021-08-23 10:35 UTC, jamebs requested changes

2021-08-23 10:35 UTC, jamebs commented on test/test_context.py
> +        results = (await pipeline.run())[0]
I think this is more readable:
```suggestion
        results, error = await pipeline.run()
```
or (if you don't care about `error`):
```suggestion
        results, _ = await pipeline.run()
```

Replace in other files, too.

2021-08-23 10:35 UTC, jamebs commented on test/test_parallel_pipeline.py
> +        print(results)
Remove print from test-file

2021-08-23 10:35 UTC, jamebs commented on test/test_sequential_pipeline.py
> +        assert isinstance(result[1], Exception)
```suggestion
        result, error = await runtime.run()
        
        assert result is None
        assert isinstance(error, Exception)
```

2021-08-23 10:35 UTC, jamebs commented on test/utils/logger/printers/test_timestamp.py
> +    @patch('magda.utils.logger.printers.timestamp.datetime')
Good catch!

2021-08-23 10:35 UTC, jamebs commented on magda/pipeline/graph.py
> +                    logger.info(f"Module {module.name} has failed. Stopping the pipeline")
`logger` has all information about pipeline and module (lines 92-96) so you don't have to write them again. However, logging the error might be useful. So, I'd recommend to wait for #20 and change to:
```suggestion
                    logger.error(e)
```

2021-08-23 10:35 UTC, jamebs commented on magda/pipeline/parallel/job.py
> +                for module_result in future.result.collection:
Can you explain this change?

2021-08-23 11:48 UTC, p-mielniczuk commented on test/test_context.py
> +        results = (await pipeline.run())[0]
Indeed, way better

2021-08-23 11:55 UTC, p-mielniczuk commented on magda/pipeline/parallel/job.py
> +                for module_result in future.result.collection:
The Graphs, Jobs, and Pipelines now make use of our Collection - ResultSet. Previously we've tended to use a list of results (List[Result]) and operate on those while having a collection that has some useful functionalities, which were never used.

So, it's better to operate on a collection with nice, predefined features wherever possible instead of raw arrays of objects.

2021-08-23 12:18 UTC, p-mielniczuk commented on magda/pipeline/graph.py
> +                    logger.info(f"Module {module.name} has failed. Stopping the pipeline")
Added a TODO

2021-08-23 13:51 UTC, jamebs requested changes

2021-08-23 13:51 UTC, jamebs commented on test/test_sequential_pipeline.py
> +        results = (await runtime.process())[0]
```suggestion
        results, _ = await runtime.process()
```

2021-08-23 13:51 UTC, jamebs commented on test/test_sequential_pipeline.py
> +        results = (await runtime.process())[0]
```suggestion
        results, _ = await runtime.process()
```

2021-08-23 13:51 UTC, jamebs commented on examples/example4.py
> +        result, err = result[0], result[1]
```suggestion
        result, err = await self.pipeline.run(Request('R'))
```

2021-08-23 13:51 UTC, jamebs commented on examples/example0.py
> +        result, err = result[0], result[1]
```suggestion
        result, err = await self.pipeline.run(Request('R'))
```

2021-08-23 13:51 UTC, jamebs commented on examples/example1.py
> +            for key, value in result[0].items():
1st Option:
```py
        for index, (result, err) in enumerate(results):
            print(f' {index}:')
            for key, value in result.items():
```

2nd option:
```py
        for index, result_object in enumerate(results):
            print(f' {index}:')
            result, err = result_object
            for key, value in result.items():
```

2021-08-23 13:51 UTC, jamebs commented on examples/example2.py
> +            for key, value in result[0].items():
Same here. I'll avoid unnamed referring positions in tuple - especially in examples, which should be self-explaining.

Please, fix in other examples too.

2021-08-23 13:51 UTC, jamebs commented on magda/pipeline/base.py
> +                raised_exception = results.collection[0]  # Always only 1 exception possible
Only 1 exception is possible (because we catch it right after it was raised), but are we sure the error is always in the first result?

2021-08-23 14:23 UTC, p-mielniczuk commented on magda/pipeline/base.py
> +                raised_exception = results.collection[0]  # Always only 1 exception possible
Uff, good catch, it's not always first. Changing it right away

2021-08-23 14:40 UTC, jamebs commented on magda/module/results.py
> +            return None
Double iterations over the whole collection (1st in `self.contains_invalid_result()`, 2nd in the method). How about *generator comprehension*:
```suggestion
        return next((result for result in self.collection if not result.isSuccessful()), None)
```

2021-08-24 14:19 UTC, DanielPopek commented on magda/module/results.py
> +    def isSuccessful(self):
Cammel case used instead of underscores. Please change.

2021-08-25 10:44 UTC, jamebs commented on magda/pipeline/parallel/job.py
> +                        return Module.ResultSet(list(self._results.values()))
This changes the flow a little bit. I've 2 suggestions:
1. This check doesn't have to be inside the for-loop - it could be right after line 88. (`future: FutureResult = task.result()`)
2. `self._status` and `self._tasks` are updated in a normal case. This termination doesn't change these values. Please, terminate tasks, update status, clean up Job before returning `ResultSet`.

2021-08-26 07:53 UTC, jamebs commented on test/test_parallel_pipeline.py
> +        result2, error2 = await pipeline.run('R2')
They should be run in parallel, so use `asyncio.gather`

2021-08-26 09:01 UTC, jamebs approved these changes
Good job! :clap:

2021-08-26 09:01 UTC, merged