Initial version of multi-level logs
NeuroSYS-pl/magda pull request #24
Opened 2021-08-20 14:45 UTC by DanielPopek

**Support different logging levels #20** 

https://github.com/NeuroSYS-pl/magda/issues/20

**Exemplary printouts:** 

Standard output: 
![image](https://user-images.githubusercontent.com/26966812/130251040-c548d6c2-1789-4ace-8591-4eb3de23b0eb.png)

Logger output:

![image](https://user-images.githubusercontent.com/26966812/130251166-2e9f7097-1653-4f54-8ab5-1e196821e3dd.png)

2021-08-23 10:13 UTC, jamebs requested changes

2021-08-23 10:13 UTC, jamebs commented on magda/utils/logger/printers/message.py
> +from ..parts import LoggerParts
Unused

2021-08-23 10:13 UTC, jamebs commented on magda/utils/logger/printers/shared.py
> +        color = Fore.WHITE
How about mapping dict?
```py
_default = (Fore.WHITE, Style.NORMAL)
_mapping = {
  LoggerParts.Level.DEBUG: (Fore.GREEN, Style.NORMAL),
  ...
}

def with_log_level_colors(text: str, level: LoggerParts.Level) -> str:
    color, style = _mapping[level] if level in _mapping else _default
    return ...
```

2021-08-23 10:13 UTC, jamebs commented on magda/utils/logger/printers/shared.py
> +
Remove empty line

2021-08-23 10:13 UTC, jamebs commented on magda/utils/logger/parts.py
> +    class Level(Enum):
You confused a little bit an idea of *Parts* and *Configs*:
*Part* is an object (dataclass) passed by the next elements of MAGDA (pipeline, group, graph, module) to logger, to print information of its source (like module name, or group to which it belongs)
*Config* is a declaration (e.g. possible logging levels, parts, output, record structure)

So, I'll move this Enum to `LoggerConfig` class and replace here with:
```py
@dataclass(frozen=True)
class Level:
    value: LoggerConfig.Level
```

Maybe we will add logs filtering based on its levels, in the future.

2021-08-23 11:36 UTC, DanielPopek commented on magda/utils/logger/printers/shared.py
> +        color = Fore.WHITE
I agree with your version - should be neater :)

2021-08-23 11:37 UTC, DanielPopek commented on magda/utils/logger/parts.py
> +    class Level(Enum):
Oh, you are right - will be changed as you described ;)

2021-08-23 13:44 UTC, DanielPopek commented on magda/utils/logger/printers/message.py
> +from ..parts import LoggerParts
Actually - it was and still is used :)

2021-08-23 14:11 UTC, jamebs requested changes

2021-08-23 14:11 UTC, jamebs commented on magda/utils/logger/parts.py
> +from enum import Enum, auto
Remove (unused)

2021-08-23 14:11 UTC, jamebs commented on magda/utils/logger/logger.py
> +            message_format.remove(LoggerConfig.Part.LEVEL)
```suggestion
        hidden_parts = []

        if config.output == MagdaLogger.Config.Output.LOGGING:
            hidden_parts.append(LoggerConfig.Part.LEVEL)
```

and then:

```py
        parts = [
            MagdaLogger._parts_mapping[key].flush(
                colors=config.colors,
                **kwargs,
            )
            for key in message_format
            if key not in hidden_parts
        ]
```

2021-08-23 14:11 UTC, jamebs commented on test/utils/logger/printers/test_level.py
> +    def test_should_print_correctly_any_level(self, level, expected_color):
Just naming, but we would like to print correctly each level - not just any of them:
```suggestion
    def test_should_print_correctly_level(self, level, expected_color):
```

2021-08-23 14:11 UTC, jamebs commented on test/utils/logger/printers/test_level.py
> +    def test_should_log_any_level_without_color_if_set(self, level):
```suggestion
    def test_should_log_level_without_color_if_set(self, level):
```

2021-08-23 14:11 UTC, jamebs commented on test/utils/logger/test_logger.py
> +            ('error', '[ERROR]')
How do you know, the level will be enclosed into these brackets? They're parameterized by formatter :smile:

2021-08-23 14:53 UTC, DanielPopek commented on test/utils/logger/test_logger.py
> +            ('error', '[ERROR]')
I change it so that the test is parametrized by LoggerConfig.Level enums. Though, I am not sure if this test should be just skipped because how the LEVEL part is presented will always depend on the formatter. Shall I remove it or we can stay with enum values ?😃

2021-08-23 15:06 UTC, jamebs commented on test/utils/logger/test_logger.py
> +            ('error', '[ERROR]')
The problem was brackets - not the level name. So this is OK `('info', 'INFO')` and this isn't: `('info', '[INFO]')`

2021-08-23 15:48 UTC, DanielPopek commented on test/utils/logger/test_logger.py
> +            ('error', '[ERROR]')
Yes, I know you mentioned brackets 😃. But I meant that in the printer we still could decide how to print the level name. - whether we would like to print for instance `WARN`,`WARNING` or `W` , `info` or `INFO` so even the level name is somehow dependant on the formatter. But I agree that we can stay with the Enum names, so I am closing the thread ;)

2021-08-23 17:35 UTC, jamebs commented on test/utils/logger/test_logger.py
> +            ('error', LoggerConfig.Level.INFO.value)
```suggestion
            ('info', LoggerConfig.Level.INFO.value),
            ('debug', LoggerConfig.Level.DEBUG.value),
            ('warn', LoggerConfig.Level.WARN.value),
            ('critical', LoggerConfig.Level.CRITICAL.value),
            ('error', LoggerConfig.Level.ERROR.value)
```

2021-08-24 07:52 UTC, p-mielniczuk commented
In MAGDA we use the convention of full path imports and don't use relative ones. Please change in all files.

2021-08-24 13:24 UTC, jamebs approved these changes
Good job! :clap:

2021-08-24 13:24 UTC, merged