Callables in ParallelPipeline
NeuroSYS-pl/magda pull request #28
Opened 2021-08-27 06:16 UTC by DanielPopek

Referring to:  https://github.com/NeuroSYS-pl/magda/issues/26

2021-08-27 06:49 UTC, DanielPopek commented on test/test_config_reader.py
> +        def callable_1():
I tried to mock callabes using @patch(), but it seems that those mocks don't work in async case, so I added ray.Queues like in bootstrap/teardown tests. However, if you see here a better solution, don't hesitate to comment 😀

2021-08-27 12:05 UTC, jamebs requested changes

2021-08-27 12:05 UTC, jamebs commented on magda/utils/logger/hooks.py
> +    logging.getLogger('magda').setLevel(logging.INFO)
You can remove this line while using `logging.DEBUG`. `DEBUG` is lower so it will also log `INFO` records

2021-08-27 12:05 UTC, jamebs commented on test/test_parallel_pipeline.py
> +            callable_1_counter.put(1)
```suggestion
            pass
```

2021-08-27 12:05 UTC, jamebs commented on test/test_config_reader.py
> +        def callable_1():
It's ok to use queues because `@patch` might not work with multi-processes scripts (like ParallelPipelines)

2021-08-27 12:54 UTC, jamebs submitted a review, later dismissed
Good job! :clap:

2021-08-30 06:49 UTC, p-mielniczuk requested changes

2021-08-30 06:49 UTC, p-mielniczuk commented on magda/pipeline/parallel/group/actor.py
> +from typing import List, Optional, List, Callable
Double List import
```suggestion
from typing import List, Optional, Callable
```

2021-08-30 06:49 UTC, p-mielniczuk commented on test/test_config_reader.py
> +        assert 3 == len(pipeline.modules)
We follow the usual convention of **actual, expected** order in tests. Please change all tests to match it.

2021-08-30 06:51 UTC, p-mielniczuk commented on test/test_config_reader.py
> +from ray.util.queue import Queue
Try to group all imports from the same library next to each other

2021-08-31 06:55 UTC, p-mielniczuk approved these changes

2021-08-31 06:56 UTC, merged