Issue 2 - Parametrization of ConfigReader
NeuroSYS-pl/magda pull request #6
Opened 2021-04-21 05:42 UTC by DanielPopek

What?
We would like to parameterize config files of pipeline declaration (similar to parameterizing docker-compose.yml with environment variables)

Why?
Sometimes you would like to run the same pipeline with just a different parameter. In this situation you have to modify the config or duplicate it (which is impractical).

How?
By updating ConfigReader to accept an optional dictionary of parameters and replacing all placeholders within the config file with an appropriate value from the provided dictionary.

@jamebs @p-mielniczuk  @mmaslankowska-neurosys

2021-04-21 07:15 UTC, jamebs commented
Closes #2

2021-04-21 20:52 UTC, jamebs requested changes

2021-04-21 20:52 UTC, jamebs commented on examples/configs/sample_config_sequential.yaml
> +    - name: m4
Missing empty line

2021-04-21 20:52 UTC, jamebs commented on examples/configs/sample_config_parallel.yaml
> +  - name: m4
Missing empty line between modules

2021-04-21 20:52 UTC, jamebs commented on examples/example4.py
> +        __location__ = os.path.realpath(
This naming convention is reserved for Python:

> `__double_leading_and_trailing_underscore__`: "magic" objects or attributes that live in user-controlled namespaces. E.g. `__init__`, `__import__` or `__file__`. **Never invent such names**; only use them as documented.

~ [PEP-8](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles)

2021-04-21 20:52 UTC, jamebs commented on examples/example4.py
> +        return os.path.join(__location__, 'configs', config_name)
```py
from pathlib import Path

...

    def get_config_file(self, config_name):
        return Path(__file__).parent / 'configs' / config_name
```

This should be enough

2021-04-21 20:52 UTC, jamebs commented on examples/example4.py
> +                {'THRESHOLD_1': 0.2, 'THRESHOLD_2': 0.2},
It will be a better example if these parameters differ

2021-04-21 20:52 UTC, jamebs commented on examples/example5.py
> +        return os.path.join(__location__, 'configs', config_name)
As above :point_up_2:

2021-04-21 20:52 UTC, jamebs commented on examples/modules/d.py
> +        log(self, ctx.timer, self.parameters['threshold'])
Make this log more verbose, e.g.
```suggestion
        log(self, ctx.timer, f"Threshold = {self.parameters['threshold']}")
```

2021-04-21 20:52 UTC, jamebs commented on magda/config_reader.py
> +    WrongParameterValueException, ConfiguartionFileException
Although there are few acceptable methods for writing multi-line imports ([PEP-328](https://www.python.org/dev/peps/pep-0328/#rationale-for-parentheses)), let's prefer `Python's standard grouping mechanism (parentheses)` over `line-breaks`

2021-04-21 20:52 UTC, jamebs commented on magda/config_reader.py
> +            warnings.warn('No config parameters passed to ConfigReader.')
It shouldn't be a warning - config doesn't have to have params

2021-04-21 20:52 UTC, jamebs commented on magda/config_reader.py
> +            cls._validate_config_parameters_structure(config_parameters)
What about the case, when `config_parameters` are not provided but config has parameters? (it should raise an exception)

2021-04-21 20:52 UTC, jamebs commented on magda/config_reader.py
> +        declared_variables = list(set(re.findall(r'\${\w*}', config_str)))
1. `\w*` accepts 0 or more chars, which is wrong - should be always at least 1 char so `\w+`
2. You can use regex groups to catch the param's name, e.g. `r'\${(\w+)}'`

2021-04-21 20:52 UTC, jamebs commented on magda/config_reader.py
> +            variable[2:-1]: variable
You can use regex group instead *positional trimming*

2021-04-21 20:52 UTC, jamebs commented on magda/config_reader.py
> +                )
You can easily find all missing parameters and throw them all at once. This will be useful when someone misses more than one param

2021-04-21 20:52 UTC, jamebs commented on magda/config_reader.py
> +            if not re.match(r'^[a-zA-Z0-9_]+$', str(key)):
Use exactly the same regex for variable names: `\w+` like in 71st line

2021-04-21 20:52 UTC, jamebs commented on magda/exceptions.py
> +        super().__init__(message)
```suggestion
    pass
```

2021-04-21 20:52 UTC, jamebs commented on magda/exceptions.py
> +        super().__init__(message)
```suggestion
    pass
```

2021-04-21 20:52 UTC, jamebs commented on magda/exceptions.py
> +        super().__init__(message)
```suggestion
    pass
```

2021-04-21 20:52 UTC, jamebs commented on test/test_config_reader.py
> +from magda.decorators.producing import produce
```suggestion
from magda.decorators import finalize, accept, produce
```

2021-04-21 20:52 UTC, jamebs commented on test/test_config_reader.py
> +from magda.module.interface import ModuleInterface
This file doesn't test `ModuleInterface` so you can remove this import and use `Module.Interface`

2021-04-21 20:52 UTC, jamebs commented on test/test_config_reader.py
> +    WrongParameterValueException, ConfiguartionFileException
Look above :point_up_2: about multi-line imports

2021-04-21 20:52 UTC, jamebs commented on test/test_config_reader.py
> +        ModuleFactory.unregister()
We don't test `ModuleFactory` within this test-suite so maybe we can use the same module definition (and only once register to the `ModuleFactory`) ?

2021-04-21 20:52 UTC, jamebs commented on test/test_config_reader.py
> +        return os.path.join(__location__, 'test_configs', config_name)
As above :point_up_2:

2021-04-21 20:52 UTC, jamebs commented on test/test_config_reader.py
> +        ModuleFactory.register('ModuleSample', ModuleSample)
Is it possible to move this *module declaration* to a file-scope or is it necessary to keep it in a test function?

2021-04-21 20:52 UTC, jamebs commented on test/test_config_reader.py
> +        config_file_with_redundant_vars = self.get_config_file(
I believe, you're checking for **excessive** config variables in this test - not *redundant*

2021-04-22 09:00 UTC, DanielPopek commented on examples/example4.py
> +        __location__ = os.path.realpath(
Definitely :) It was nearly copy-pasted from test_interfaces.py. I propose changing the method also in test files.

2021-04-22 09:05 UTC, DanielPopek commented on examples/example4.py
> +        return os.path.join(__location__, 'configs', config_name)
Agree. Much neater solution :)

2021-04-22 09:13 UTC, DanielPopek commented on examples/modules/d.py
> +        log(self, ctx.timer, self.parameters['threshold'])
Good point

2021-04-22 09:18 UTC, DanielPopek commented on magda/config_reader.py
> +    WrongParameterValueException, ConfiguartionFileException
Okay, I don't mind. We could stick to parentheses convention :)

2021-04-22 09:25 UTC, DanielPopek commented on magda/exceptions.py
> +        super().__init__(message)
Correct :)  Constructors in case of these exceptions.

2021-04-22 09:30 UTC, DanielPopek commented on test/test_config_reader.py
> +from magda.module.interface import ModuleInterface
Good point

2021-04-22 09:35 UTC, DanielPopek commented on test/test_config_reader.py
> +        config_file_with_redundant_vars = self.get_config_file(
I do agree - **excessive** seems to be a better expression.

2021-04-22 09:37 UTC, DanielPopek commented on test/test_config_reader.py
> +        ModuleFactory.register('ModuleSample', ModuleSample)
The module is used only in this test function, so I would rather leave it within its scope.

2021-04-22 14:37 UTC, DanielPopek commented on test/test_config_reader.py
> +        ModuleFactory.unregister()
That is right :) To be honest, we don't need module _ModuleDependingCorrect_  to be declared in the file scope, as it is only used within one test function. I am changing its name to _DependingModule_, moving and registering it only once in _test_should_pass_with_correct_variables_in_config_

2021-04-22 14:37 UTC, DanielPopek commented on magda/config_reader.py
> +            if not re.match(r'^[a-zA-Z0-9_]+$', str(key)):
Changed to ### r'^\w+$'

2021-04-22 14:39 UTC, DanielPopek commented on magda/config_reader.py
> +                )
I agree. It would be a better solution

2021-04-22 14:39 UTC, DanielPopek commented on magda/config_reader.py
> +            variable[2:-1]: variable
Good point - I refactored it.

2021-04-22 14:40 UTC, DanielPopek commented on magda/config_reader.py
> +        declared_variables = list(set(re.findall(r'\${\w*}', config_str)))
My bad :) Good that you noticed. Will be refactored

2021-04-22 14:41 UTC, DanielPopek commented on magda/config_reader.py
> +            cls._validate_config_parameters_structure(config_parameters)
My bad :) Good that you noticed. Will be refactored

2021-04-22 14:42 UTC, DanielPopek commented on magda/config_reader.py
> +            warnings.warn('No config parameters passed to ConfigReader.')
Agree :)

2021-04-22 15:08 UTC, jamebs approved these changes

2021-04-22 15:11 UTC, merged